---
- name: clone nix-build-pack-docker
  git: repo=https://github.com/datakurre/nix-build-pack-docker.git dest=/root/nix-build-pack-docker

- name: install docker-py
  pip: name=docker-py

- name: build nix-builder image
  shell: cd /root/nix-build-pack-docker && docker build -t nix-builder -f nix-builder.docker --rm=true --force-rm=true --no-cache=true .
